---
- name: Insall zabbix agent
  yum: name=zabbix-agent state=installed
- name: Config zabbix agent
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
- name: Run zabbix agent
  service: name=zabbix-agent state=started enabled=yes
- include: "{{ action }}.yml"
  when: action is defined
  notify: restart zabbix agent

