<<<<<<< HEAD

=======
---
repo_url: http://www.ex.ua/get/231948339
repo_file: /home/vagrant/repo.tar.gz
repo_dest: /var/www/html/localrepo/
ex_path: /var/www/html
>>>>>>> 901365d1dbc0feffa5a6178a674ddbf5f20da1b6
