---
zabbix_user: Admin
zabbix_user_password: zabbix
action: 'install'
zabbix_url: http://zabbix/zabbix
database_name: 'zabbix'
path_from_copy: /usr/share/doc/zabbix-server-mysql-2.4.7/create/
path_to_files: /usr/share/doc/zabbix-server-mysql-2.4.7/create/
files_to_import: ["schema.sql","images.sql","data.sql"]
host_ip: "{{ ansible_eth0.ipv4.address }}"
host_name: "{{ ansible_hostname }}"

zabbix_groups_for_create:
  - DB
  - WEB
  - LOGSERVER
  - REPO
  - JENKINS
  - BALANCER

host_template:
  - Template ICMP Ping
  - Template OS Linux

