---
- hosts: database
  tasks: 
  - name: include Name
    include_vars: ./roles/mysql/vars/main.yml
#- include_vars: 

  - name: OMS MySQL databases.
    mysql_db: 
      name="{{ name_db_oms }}"  
      collation="utf8_general_ci"
      encoding="utf8"
      state=present
#      when: {{ name_db_oms }}|lower() != 'none'

      
  - name: Create the database users
    mysql_user: name={{ user_db_oms }}  password={{ pass_db_oms }} priv="*.*:ALL" state=present host="localhost"
#    when: {{ user_db_oms }}|lower() != 'none'
