---
- hosts: repo
  remote_user: root
  sudo: yes

  vars:
    download_url: "http://apache.ip-connect.vn.ua/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz"
    download_folder: /usr
    app_name: "{{download_folder}}/apache-maven-3.3.9"
    extra_path: "{{app_name}}/bin"
    app_archive: "{{download_folder}}/apache-maven-3.3.9-bin.tar.gz"

  tasks:
  - name: Download Maven
    get_url: url={{download_url}} dest={{app_archive}}

  - name: Unpack archive
    command: "tar -zxf {{app_archive}} -C {{download_folder}} creates={{app_name}}"

  - name: Set MAVEN_HOME
    lineinfile: dest=/etc/environment state=present
     regexp='^MAVEN_HOME'
     line='MAVEN_HOME="{{app_name}}"'

  - name: Set M2_HOME
    lineinfile: dest=/etc/environment state=present
     regexp='^M2_HOME'
     line='M2_HOME="{{app_name}}"'

  - name: add {{extra_path}} to path
    lineinfile: dest=/etc/environment state=present
     backrefs=yes
     regexp='PATH=(["]*)((?!.*?{{extra_path}}).*?)(["]*)$'
     line="PATH=\1\2:{{extra_path}}\3"
















 