---

- name: Install Maven
  yum: name=maven state=present

- name: Modify etc environment
  lineinfile:  dest="/etc/environment"  line='{{item}}'
  with_items:
  - 'M2_HOME="/usr/share/maven"'
  - 'M2="/usr/share/maven"'
  - 'MAVEN_HOME="/usr/share/maven"'

- name: Set Maven extra_path
  set_fact: mvn_extra_path="/usr/share/maven/bin"
  
- name: Add {{mvn_extra_path}} to path
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?{{mvn_extra_path}}).*?)(["]*)$' line="PATH=\1\2:{{mvn_extra_path}}\3"

