---
root_db_password: 123
name_db_replic: omsdb
user_db_replic: replic_user
pass_db_replic: 123
name_dumpfile: dump_oms.sql
name_db_oms: omsdb
user_db_oms: 056db
pass_db_oms: 056db


MySQLReplication:
 role: master
 user: replic_user
 userPassword: 123
   




      
# A list of the mysql DB to be created
mysql_db:                              
  - name: omsdb
    host: "%"
    pass: omsdb


# A list of the mysql users to be created
# and their password and privileges:
mysql_users:                              
  - name: 056db
    host: "%"
    pass: 056db
    priv: "omsdb.*:ALL"
  - name: 055db
    host: "%"
    pass: 055db
    priv: "*.*:ALL"
                            
# If the database is replicated the users
# to be used for replication:
mysql_repl_user:                          
  - name: repl
    pass: repl