---
# Install simple FTP server
  - name: Install vsftpd package
    yum: name=vsftpd state=latest

 # Run  FTP server
  - service: name=vsftpd enabled=yes
  - service: name=vsftpd state=started

 # Instal dependencies
  - name: install selinux bindings (for lineinfile work)
    yum: name=libselinux-python state=present  
  - name: Install the following dependencies for createrepo 1
    yum: name=libxml2-python state=present
  - name: Install the following dependencies for createrepo 2
    yum: name=deltarpm state=present
  - name: Install the following dependencies for createrepo 3
    yum: name=python-deltarpm state=present

 # Instal createrepo
  - name: Install createrepo
    yum: name=createrepo state=present

 # Create directory for repo 
  - name: Create a storage location in our FTP server pub directory.
    file: path=/var/ftp/pub/localrepo state=directory

  - name: Install wget
    yum: name=wget state=present

  - name: Download Java
    command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"

  - name: Download Maven
    get_url: url={{download_url1}} dest={{app_archive1}}

  - name: Download Tomcat
    get_url: url={{download_url2}} dest={{app_archive2}}

  - name: Download Jenkins
    get_url: url={{download_url3}} dest={{app_archive3}}

 # Create a repository file called “localrepo.repo” under /etc/yum.repos.d/
  - lineinfile: dest=/etc/yum.repos.d/localrepo.repo
     regexp='^'
     line='[localrepo]\nname=IF061DevOps Repository\nbaseurl=file:///var/ftp/pub/localrepo\ngpgcheck=0\nenabled=1'
     create=True

 #Build local repository:
  - name: start building local repository
    command: createrepo -v /var/ftp/pub/localrepo/

  - name: cleaning task for yum
    command: /usr/bin/yum clean all

  - name: upgrade all packages
    yum: name=* state=latest
