---

- name: Create {{ database_name }} Database
  mysql_db: 
    name={{ database_name }} 
    state=present
  register: db_exist


- name: Import DB 
  mysql_db:
    name={{ database_name }}
    state=import
    target={{ path_to_files }}{{ item }}
  with_items: 
    - "{{ files_to_import }}" 
  when: db_exist.changed
