 - hosts: [database]
   tasks:
#   - name: Create the database's
#...
...
#   - name: Create MySQL user for user
#     mysql_user: name=056oms priv=oms.*:ALL password=056oms login_user=root log
..
    - name: Create MySQL root password
      mysql_user: name=root priv=*.*:ALL,GRANT password=123 login_user=root login_password=123 chek_implicit_admin=True
......
    - name: Create the database's
      mysql_db: 
               name=omsdb
               collation=utf8_swedish_ci
               encoding=utf8
               state=present login_user=root login_password=123
....
    - name: Create MySQL user for user
      mysql_user: name=056db priv=omsdb.*:ALL password=056db login_user=root login_password=123
......
......
