---
- name: Install Jenkins
  yum: state=present name={{ item }}
  with_items:
  - jenkins
  - git

- name: Start Jenkins
  service: name=jenkins state=started enabled=yes

- name: Create Jenkins Plugins folder
  file: path={{ jenkins_home }}/plugins/ mode=0775 owner=jenkins group=jenkins state="directory" recurse=yes

- name: Install plugins
  get_url: url=http://updates.jenkins-ci.org/latest/{{ item }}.hpi dest={{ jenkins_home }}/plugins/{{ item }}.hpi
  with_items:
  - git
  - git-client
  - git-parameter
  - scm-api
  - git-tag-message
  - publish-over-ssh

- name: Create Jenkins Master Jobs folder
  file: path={{ jenkins_home }}/jobs/oms-master/ mode=0775 owner=jenkins group=jenkins state="directory" recurse=yes

- name: Create Jenkins Dev Jobs folder
  file: path={{ jenkins_home }}/jobs/oms-dev/ mode=0775 owner=jenkins group=jenkins state="directory" recurse=yes

- name: Config Jenkins Dev Job
  template: src=config-job-dev.xml dest={{ jenkins_home }}/jobs/oms-dev/config.xml

- name: Config Jenkins Master Job
  template: src=config-job-master.xml dest={{ jenkins_home }}/jobs/oms-master/config.xml

- name: Config Jenkins
  template: src={{ item }} dest={{ jenkins_home }}/{{ item }} owner=jenkins group=jenkins mode=0644
  with_items:
  - config.xml
  - hudson.tasks.Maven.xml
  - jenkins.mvn.GlobalMavenConfig.xml
  - jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml
  notify: restart jenkins
