---
- name: Install Jenkins
  yum: state=present name={{ item }}
  with_items:
  - jenkins
  - git
  - rpm-build

- name: Start Jenkins
  service: name=jenkins state=started enabled=yes

- name: Install plugins
  get_url: url=http://updates.jenkins-ci.org/latest/{{ item }}.hpi dest=/var/lib/jenkins/plugins/{{ item }}.hpi
  with_items:
  - git
  - git-client
  environment:
    http_proxy: 192.168.5.103:8080
- name: Install plugins
  get_url: url=http://updates.jenkins-ci.org/download/plugins/scm-api/1.1/scm-api.hpi dest=/var/lib/jenkins/plugins/scm-api.hpi
  environment:
    http_proxy: 192.168.5.103:8080
  notify: restart jenkins