---

  - name: Create Master for MySQL replication
    include_vars: main.yml
     
  - name: Ensure Service is Started and Enabled
    service: name=mysql state=started enabled=yes
    sudo: yes

    
  - name: Modify configuration file to listen on all interfaces
    ini_file: dest=/etc/my.cnf.d/server.cnf
              section=mysqld
              option=bind-address
              value=0.0.0.0
              backup=yes
  - name: Modify configuration file to setup server ID
    ini_file: dest=/etc/my.cnf.d/server.cnf
              section=mysqld
              option=server-id
              value=1
  - name: Modify configuration file to setup bin.log
    ini_file: dest=/etc/my.cnf.d/server.cnf
              section=mysqld
              option=log_bin
              value=/tmp/mysql-bin.log

                                          
  - name: Modify configuration file to setup binlog_do_db
    ini_file: dest=/etc/my.cnf.d/server.cnf
              section=mysqld
              option=binlog_do_db
              value={{name_db_oms}}


  - name: Restart mysql service
    service: name=mysql state=restarted enabled=yes
    sudo: yes

  - name: Create replication account 111
    mysql_user: name={{ user_db_replic }}
                host=%
                password={{ pass_db_replic }}
                priv="*.*:REPLICATION SLAVE"
                state=present
     
  - name: Reset master binlog
    command: mysql -u root -e "RESET MASTER"


# old style
#  - name: Reset master binlog
#    command: mysql -u root -e "FLUSH TABLES WITH READ LOCK;"


# FLUSH TABLES WITH READ LOCK;
# SET GLOBAL read_only = ON;

#master# mysqldump -u root -p --lock-all-tables [dbname] > dbdump.sql
#mysql@master> SET GLOBAL read_only = OFF;


# mysqldump -u root -p {{name_db_oms}} > /tmp/{{name_db_oms}}.sql




#  - name: step 2
#    user: root
#    hosts: db2
#    tasks:
#    - include: start_slave.yml

