---
- name: Create destination folder and set permissions
  file: path=/src/OMS mode=0775 owner=root group=root state="directory" recurse=yes

- name: Install GIT
  yum: pkg=git state=installed

- name: Clone OMS
  git: 
    repo={{ remote_repository }}
    dest=/src/OMS
    clone=yes
    update=yes

    
