---
# Install Repoisitory
- hosts: repository
  become: yes
  user: vagrant
  roles:
  - { role: apache2 }
  - { role: repository, action: 'download', repo_dir: "{{ _repos }}" }
  - { role: zabbixagent, action: 'zabbixcreatehost', host_group: 'REPO'}


# Pre-install for all hosts
- hosts: all
  roles:
  - setlocalrepo
  - zabbixagent
 

# Install Logserver

- hosts: logs
  roles:
  - java7
  - logging
  - { role: zabbixagent, action: 'zabbixcreatehost', host_group: 'LOGSERVER'}


# Create zabbix-server

- hosts: zabbix
  roles:
  - setlocalrepo
  - { role: apache2, action: 'virtualhost', zabbix_config: 'yes', vhost_name: 'zabbix', vhost_dir: '/usr/share/zabbix' }
  - { role: mysql }
  - { role: zabbixserver }
  - { role: mysql, action: 'create-user',  database_user: 'zabbix', database_password: 'zabbix' }
  - { role: zabbixserver, action: 'zabbixcreatedb' }
- hosts: zabbix
  roles:
  - { role: zabbixserver, action: 'zabbixcreategroup' }

# Install MySql for DB group
  
  hosts: database
  roles:
    - {role: mysql10, action: 'create-oms', replication: 'yes'}
    - { role: zabbixagent, action: 'zabbixcreatehost', host_group: 'DB'}
# Setup CI

- hosts: ci
  roles:
  - java7
  - maven
  - { role: mysql, action: 'install' }
  - { role: mysql, action: 'change-root-passwords' }
  - { role: mysql, action: 'create-database', database_name: 'omsdb' }
  - { role: mysql, action: 'create-user',  database_user: '056db', database_password: '056db' }
  - { role: jenkins, action: 'install' }
  - { role: jenkins, action: 'plugins', jenkins_plugin: "{{ _jenkins_oms_plg }}" }
  - { role: oms, action: 'configure-jenkins' }
  - { role: zabbixagent, action: 'zabbixcreatehost', host_group: 'JENKINS'}

# Install httpd for WEB group
- hosts: webapp
  roles:
  - java7
  - { role: tomcat, tomcat_http_port: 8080}
  - { role: oms, action: 'install' }
  - consul
  - { role: zabbixagent, action: 'zabbixcreatehost', host_group: 'WEB'}
# Install balancer

- hosts: balancer
  roles:
  - consul-template
  - { role: zabbixagent, action: 'zabbixcreatehost', host_group: 'BALANCER'}

