---
  - name: include Name
    include_vars: ./../roles/mysql10/vars/main.yml

  - name: ensure anonymous users are not in the database
    mysql_user: name='' state=absent
  
  - name: create the database users OMS
    mysql_user: name={{ item.name }} 
                host={{ item.host }} 
                password={{ item.pass }} 
                priv={{ item.priv }} state=present
    with_items: mysql_users
    when: mysql_db|lower() != 'none'

#
# Create database
#

  - name: remove the test database
    action: mysql_db db=test state=absent
                                
  - name: create the databases OMD
    mysql_db: name="{{ name_db_oms }}"
              collation="utf8_general_ci"
              encoding="utf8"
              state=present

#  - name: Open potr 3306 for MySQL
#    sudo: yes
#    command: firewall-cmd --permanent --zone=trusted --add-source=0.0.0.0/0
#    command: firewall-cmd --permanent --zone=trusted --add-port=3306/tcp
#    command: firewall-cmd  --reload
    
    
