---
- name: run zabbix-agent
  hosts: all
  become: yes
  user: vagrant

  roles:
   - setlocalrepo
   - { role: zabbixagent, 
       action: 'zabbixcreatehost', 
       host_group: "{{ group_names }}"
     }

