---
- hosts: webapp
  remote_user: vagrant
  become: yes

  roles:
  - setlocalrepo
  - java7
  - tomcat
  - { role: apache2, action: 'virtualhost', indexes: "+Indexes" }
  - { role: oms, action: 'configure-vhost' }
  - oms



