---
- name: run zabbix-agent
  hosts: webapp
  become: yes
  user: vagrant

  roles:
   - setlocalrepo
   - { role: zabbixagent, 
       action: 'zabbixcreatehost', 
       host_group: ['REPO','DB'] 
     }

